[profile.default]
via-ir=true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
extra_output_files = ["metadata"]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
evm_version = 'istanbul'
optimizer = true
runs = 1000
[fmt]
single_line_statement_blocks = "multi"
multiline_func_header = "all"
sort_imports = true
contract_new_lines = true
override_spacing = true
line_length = 80
tab_width = 4
[doc]
repository = "https://github.com/ambrosus/token-bridge"
[profile.coverage]
via-ir=true
no-match-coverage="test/.*.sol"
report-file="./coverage/lcov.info"
[profile.ci]
via-ir=true
verbosity=3
ffi=true
force=true
no-match-coverage="test/.*.sol"
report-file="./coverage/lcov.info"

