[profile.default]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
evm_version = 'istanbul'