[profile.default]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'
evm_version = 'istanbul'
[fmt]
single_line_statement_blocks = "multi"
multiline_func_header = "all"
sort_imports = true
contract_new_lines = true
override_spacing = true
line_length = 80
tab_width = 4
[doc]
repository = 'https://github.com/ambrosus/token-bridge'
